apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    app: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-feed
  template:
    metadata:
      labels:
        app: api-feed
    spec:
      containers:
        - name: api-feed
          image: quocpq/udagram-api-feed
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: project3-env-config
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: project3-env-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: project3-env-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: project3-env-config
                  key: POSTGRES_DB
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: project3-env-config
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: project3-env-config
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: project3-env-config
                  key: AWS_PROFILE
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: project3-env-config
                  key: JWT_SECRET
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: project3-env-config
                  key: URL
          ports:
            - containerPort: 80
      volumes:
        - name: project3-aws-secret
          secret:
            secretName: project3-aws-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-feed
  name: api-feed
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: api-feed  
        
