apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - image: quocpq/reverseproxy
          name: reverseproxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              # memory: "1024Mi"
              cpu: "1000m"
            requests:
              # memory: "64Mi"
              cpu: "500m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: reverseproxy